site_name: Ploopy Classic 2 Trackball
site_url: https://ploopyco.github.io/classic-2-trackball
theme: material
nav:
  - 'index.md'
  - 'assembly-instructions.md'
  - Appendices:
    - 'appendices/pcbs.md'
    - 'appendices/3d-printing.md'
    - 'appendices/hardware.md'
    - 'appendices/programming.md'
  - 'license.md'